name: CTSockets
description: No more Plugin Messaging Channels!
main: de.crafttogether.ctsockets.bukkit.CTSockets
api-version: 1.13
version: 1.2.1-SNAPSHOT
build: 
author: J0schlZ
website: https://github.com/J0schlZ/CTSockets/
commands:
  ctsockets:
    description: Type "/ctsockets help" for more Information.
    usage: /ctsockets help
    aliases:
    - cts
permissions:
  ctsockets.list:
    description: List connected servers
    default: op
  ctsockets.ping:
    description: Ping another server
    default: op
  ctsockets.sync:
    description: Run command on another server
    default: op